# Generated by Django 5.2.5 on 2025-08-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_min', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibre',
            name='decrypted_application',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fibre',
            name='decrypted_color_of_fibre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fibre',
            name='decrypted_fibre_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fibre',
            name='decrypted_quantity_of_fibre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fibre',
            name='encrypted_application',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fibre',
            name='encrypted_color_of_fibre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fibre',
            name='encrypted_fibre_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fibre',
            name='encrypted_quantity_of_fibre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fibre',
            name='form_decryption_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
