# Generated by Django 5.2.5 on 2025-08-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_min', '0003_rename_available_seed_space_fibre_additives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibre',
            name='argon_gas',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fibre',
            name='energy_use',
            field=models.FloatField(null=True),
        ),
    ]
